version: '3.8'

services:
  backend:
    build: .
    container_name: gitvibe-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    env_file:
      - .env.docker
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: >
      sh -c "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  redis:
    image: redis:7-alpine
    container_name: gitvibe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    command: redis-server --appendonly yes

volumes:
  redis_data:
