version: '3.8'

services:
  frontend:
    build:
      context: ./gitvibe-next
      dockerfile: Dockerfile
    container_name: gitvibe-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_API_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    networks:
      - gitvibe-network
    restart: unless-stopped

  backend:
    build:
      context: ./gitvibe-backend
      dockerfile: Dockerfile
    container_name: gitvibe-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ENVIRONMENT=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./gitvibe-backend/app:/app/app
    networks:
      - gitvibe-network
    restart: unless-stopped

networks:
  gitvibe-network:
    driver: bridge
